<?php

$factory->define(App\Patient::class, function (Faker\Generator $faker) {
    return [
        "txt_start_date" =>date("2019-5-5"),
        "tb_no" => $faker->name,
        "name" => $faker->name,
        "sex" => collect(["1","0",])->random(),
        "dob" => $faker->date("Y-m-d", $max = 'now'),
        "age"=> $faker->randomNumber(2),
        "current_address" => $faker->name,
        "report_person_id" => collect(["2","3",])->random(),
        "health_facility_id" => collect(["1","2",])->random(),
        "phone" => $faker->name,
        "referred_by" => $faker->name,
        "permanent_address" => $faker->name,
        "dot_provider" => $faker->name,
        "dots_supervisor" => $faker->name,
        "contact_person" => $faker->name,
        "type_of_patient" => collect(["1","2","3","4","5","6","7",])->random(),
        "tb_site" => collect(["1","0",])->random(),
        "regimen" => collect(["1","2","3",])->random(),
        "smear_result_0" => collect([NULL,0,])->random(),
        "x_pert_result" => collect([Null, 0])->random(),
        "culture_result" => $faker->randomNumber(2),
        "dst_h_0" => $faker->randomNumber(2),
        "dst_r_0" => $faker->randomNumber(2),
        "dst_e_0" => $faker->randomNumber(2),
        "lpa_e_0" => $faker->randomNumber(2),
        "lpa_r_0" => $faker->randomNumber(2),
        "weight" => $faker->randomNumber(2),
        "smear_result_2" => $faker->randomNumber(2),
        "xpert_result_2" => $faker->randomNumber(2),
        "culture_result_2" => $faker->randomNumber(2),
        "dst_h_2" => $faker->randomNumber(2),
        "dst_r_2" => $faker->randomNumber(2),
        "dst_s_2" => $faker->randomNumber(2),
        "dst_e_2" => $faker->randomNumber(2),
        "lpa_h_2" => $faker->randomNumber(2),
        "lpa_r_2" => $faker->randomNumber(2),
        "wt_2" => $faker->randomNumber(2),
        "smear_result_5" => $faker->randomNumber(2),
        "xpert_result_5" => $faker->randomNumber(2),
        "culture_result_5" => $faker->randomNumber(2),
        "dst_h_5" => $faker->randomNumber(2),
        "dst_r_5" => $faker->randomNumber(2),
        "dst_s_5" => $faker->randomNumber(2),
        "dst_e_5" => $faker->randomNumber(2),
        "lpa_h_5" => $faker->randomNumber(2),
        "lpa_r_5" => $faker->randomNumber(2),
        "wt_5" => $faker->randomNumber(2),
        "smear_result_e" => $faker->randomNumber(2),
        "xpert_result_e" => $faker->randomNumber(2),
        "culture_result_e" => $faker->randomNumber(2),
        "dst_h_e" => $faker->randomNumber(2),
        "dst_r_e" => $faker->randomNumber(2),
        "dst_s_e" => $faker->randomNumber(2),
        "dst_e_e" => $faker->randomNumber(2),
        "lpa_h_e" => $faker->randomNumber(2),
        "lpa_r_e" => $faker->randomNumber(2),
        "wt_e" => $faker->randomNumber(2),
        "c_regimen" => $faker->randomNumber(2),
        "hiv_test_result" => collect(["1","2","3",])->random(),
        "hiv_test_date" => $faker->date("Y-m-d", $max = 'now'),
        "cpt" => $faker->date("Y-m-d", $max = 'now'),
        "art" => $faker->date("Y-m-d", $max = 'now'),
        "outcome" => collect(["1","2","3","4","5","6","7",])->random(),
    ];
});
