<?php

$factory->define(App\Patient::class, function (Faker\Generator $faker) {
    return [
        "txt_start_date" =>$faker->dateTimeBetween('now - 1 years', 'now + 1 years')->format('Y-m-d'),
        "tb_no" => $faker->name,
        "name" => $faker->name,
        "sex" => collect(["1","0",])->random(),
        "dob" => $faker->date("Y-m-d", $max = 'now'),
        "age"=> $faker->numberBetween(15, 70),
        "current_address" => $faker->name,
        "report_person_id" => collect(["2","3",])->random(),
        "health_facility_id" => collect(["1","2",])->random(),
        "phone" => $faker->name,
        "referred_by" => $faker->name,
        "permanent_address" => $faker->name,
        "dot_provider" => $faker->name,
        "dots_supervisor" => $faker->name,
        "contact_person" => $faker->name,
        "type_of_patient" => collect(["1","2"])->random(),
        "tb_site" => collect(["1","0",])->random(),
        "regimen" => collect(["1","2","3",])->random(),
        "smear_result_0" => collect([0,1])->random(),
        "x_pert_result" => collect([Null, 0,1,2,3])->random(),
        "culture_result" => collect([NULL,0,1,1])->random(),
        "dst_h_0" => collect(["1","2","3",])->random(),
        "dst_e_0" => collect(["1","2","3",])->random(),
        "lpa_e_0" => collect(["1","2","3",])->random(),
        "lpa_r_0" => collect([NULL,0,1])->random(),
        "weight" => collect([NULL,0,1])->random(),
        "smear_result_2" => collect([NULL,0,1])->random(),
        "xpert_result_2" => collect([NULL,0,1])->random(),
        "culture_result_2" => collect([NULL,0,1])->random(),
        "dst_h_2" => collect([NULL,0,1])->random(),
        "dst_r_2" => collect([NULL,0,1])->random(),
        "dst_s_2" => collect([NULL,0,1])->random(),
        "dst_e_2" => collect([NULL,0,1])->random(),
        "lpa_h_2" => collect([NULL,0,1])->random(),
        "lpa_r_2" => collect([NULL,0,1])->random(),
        "wt_2" => collect([NULL,0,1])->random(),
        "smear_result_5" => collect([NULL,0,1])->random(),
        "xpert_result_5" => collect([NULL,0,1])->random(),
        "culture_result_5" => collect([NULL,0,1])->random(),
        "dst_h_5" => collect([NULL,0,1])->random(),
        "dst_r_5" => collect([NULL,0,1])->random(),
        "dst_s_5" => collect([NULL,0,1])->random(),
        "dst_e_5" => collect([NULL,0,1])->random(),
        "lpa_h_5" => collect([NULL,0,1])->random(),
        "lpa_r_5" => collect([NULL,0,1])->random(),
        "wt_5" => collect([NULL,0,1])->random(),
        "smear_result_e" => collect([NULL,0,1])->random(),
        "xpert_result_e" => collect([NULL,0,1])->random(),
        "culture_result_e" => collect([NULL,0,1])->random(),
        "dst_h_e" => collect([NULL,0,1])->random(),
        "dst_r_e" => collect([NULL,0,1])->random(),
        "dst_s_e" => collect([NULL,0,1])->random(),
        "dst_e_e" => collect([NULL,0,1])->random(),
        "lpa_h_e" => collect([NULL,0,1])->random(),
        "lpa_r_e" => collect([NULL,0,1])->random(),
        "wt_e" => collect([NULL,0,1])->random(),
        "c_regimen" => collect([NULL,0,1])->random(),
        "hiv_test_result" => collect(["1","2","3",])->random(),
        "hiv_test_date" => $faker->date("Y-m-d", $max = 'now'),
        "cpt" => $faker->date("Y-m-d", $max = 'now'),
        "art" => $faker->date("Y-m-d", $max = 'now'),
        "outcome" => collect(["1","2","3","4","5","6","7",])->random(),
    ];
});
